// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/gin-gonic/gin"
	"github.com/ranryl/go-ddd/internal/biz"
	"github.com/ranryl/go-ddd/internal/data"
	"github.com/ranryl/go-ddd/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Initialize(dsn data.DBDSN, config *gorm.Config) *gin.Engine {
	dataData := data.NewData(dsn, config)
	clusterRepo := data.NewClusterRepo(dataData)
	clusterCase := biz.NewClusterCase(clusterRepo)
	clusterService := service.NewClusterService(clusterCase)
	engine := NewRouter(clusterService)
	return engine
}
